version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    env_file: ".env-postgresql"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  django_polls:
    build: .
    env_file: ".env-django"
    volumes:
      - static_files:/app/staticfiles
    ports:
      - 8000:8000
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres:
  static_files:
